-- Maharani Saree Collection: run this once in Supabase SQL Editor.
create table if not exists public."Orders" (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  bill_no text not null unique,
  customer_name text not null default '',
  mobile text not null default '',
  address text not null default '',
  pin text not null default '',
  items jsonb not null default '[]'::jsonb,
  subtotal numeric not null default 0,
  discount numeric not null default 0,
  total numeric not null default 0,
  status text not null default 'Pending',
  gst text not null default '10BZYPB5853J1Z3'
);

alter table public."Orders" enable row level security;

grant insert on table public."Orders" to anon;
grant select,insert,update,delete on table public."Orders" to authenticated;

drop policy if exists "Public can create online orders" on public."Orders";
create policy "Public can create online orders"
on public."Orders" for insert to anon
with check (true);

drop policy if exists "Admin can read orders" on public."Orders";
create policy "Admin can read orders"
on public."Orders" for select to authenticated
using (true);

drop policy if exists "Admin can update orders" on public."Orders";
create policy "Admin can update orders"
on public."Orders" for update to authenticated
using (true) with check (true);

drop policy if exists "Admin can delete orders" on public."Orders";
create policy "Admin can delete orders"
on public."Orders" for delete to authenticated
using (true);
